name: Ansible

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ANSIBLE_HOST_KEY_CHECKING: False
      AWS_ACCESS_KEY_ID: ${{ secret.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secret.AWS_SECRET_KEY }}

    steps:
      # Checkout/Clone Repo
      - uses: actions/checkout@v3

      - name: Check Ansible Version
        run: ansible --version

      - name: Install boto3, botocore
        run: |
          . /opt/pipx/venvs/ansible-core/bin/activate
          /opt/pipx/venvs/ansible-core/bin/python -m pip install boto3 botocore

      - name: Test Inventory
        run: ansible -i aws_ec2.yml --private-key ansible-key  -m ping  all


