name: Ansible

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Ansible Version
        run: ansible --version

      - name: Test Inventory
        run: ansible -i aws_ec2.yml --private-key ansible-key  -m ping  all


